// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxeiwmwuybyueyybpqye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4ZWl3bXd1eWJ5dWV5eWJwcXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTIwMjEsImV4cCI6MjA1ODY2ODAyMX0.cjsWx4IuLcl4ykjCFDjLLQ8k9GCNh18SScHXdM7lVPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);